# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
use_frameworks!

target 'IceCreamShop' do
	pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :branch => 'swift-2.0'
	pod 'MBProgressHUD', '~> 0.9.0'
end

target 'IceCreamShopTests' do

end

